const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('.map-state').waitFor({state:'hidden'});
  assert.equal(await page.locator('.leaflet-overlay-pane path[fill-opacity="0.65"]').count(),380);
  const before = await page.locator('.legend').innerText();
  await page.getByLabel('Rainfall scenario').selectOption('extreme');
  await page.locator('.map-state').waitFor({state:'hidden'});
  const after = await page.locator('.legend').innerText(); assert.notEqual(before,after);
  await page.locator('.leaflet-overlay-pane path[fill-opacity="0.65"]').first().dispatchEvent('click');
  await page.getByLabel('Village detail', {exact:true}).waitFor();
  await page.getByLabel('Highlight SAR change zones').check();
  await page.screenshot({path:'docs/evidence/m4-dashboard.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({path:'docs/evidence/m4-mobile.png',fullPage:true});
  await page.route('**/scenarios/evaluate', route => route.fulfill({status:503,contentType:'application/json',body:'{}'}));
  await page.getByLabel('Rainfall scenario').selectOption('heavy');
  await page.getByRole('alert').waitFor();
  await page.screenshot({path:'docs/evidence/m4-error.png',fullPage:true});
  await page.unroute('**/scenarios/evaluate');
  await page.getByRole('button',{name:'Retry data'}).click();
  await page.locator('.map-state').waitFor({state:'hidden'});
  await page.route('**/scenarios/evaluate', async route => { await new Promise(r=>setTimeout(r,1000)); await route.continue(); });
  await page.getByLabel('Rainfall scenario').selectOption('normal');
  await page.getByText('Loading real study data…').waitFor();
  await page.locator('.map-state').waitFor({state:'hidden'});
  assert.deepEqual(errors,[]);
  const result={villages:380,scenario_recolors:true,detail:true,mobile_no_overflow:true,error_and_retry:true,loading:true,errors};
  fs.writeFileSync('docs/evidence/m4-browser.json',JSON.stringify(result,null,2));console.log(result);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
